# Generated by Django 5.1.4 on 2025-06-26 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=25)),
                ('stock', models.PositiveIntegerField()),
                ('detalles', models.CharField(max_length=500)),
                ('usuarios', models.ManyToManyField(related_name='categorias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
